interface memory {
    record memory-info {
        mem-total: u64,
        mem-free: u64,
        mem-available: u64,
        buffers: u64,
        cached: u64,
        swap-cached: u64,
        active: u64,
        inactive: u64,
        active-anon: u64,
        inactive-anon: u64,
        active-file: u64,
        inactive-file: u64,
        unevictable: u64,
        mlocked: u64,
        swap-total: u64,
        swap-free: u64,
        dirty: u64,
        writeback: u64,
        anon-pages: u64,
        mapped: u64,
        shmem: u64,
        kreclaimable: u64,
        slab: u64,
        sreclaimable: u64,
        sunreclaim: u64,
        kernel-stack: u64,
        page-tables: u64,
        nfs-unstable: u64,
        bounce: u64,
        writeback-tmp: u64,
        commit-limit: u64,
        committed-as: u64,
        vmalloc-total: u64,
        vmalloc-used: u64,
        vmalloc-chunk: u64,
        percpu: u64,
        cma-total: option<u64>,
        cma-free: option<u64>,
        hardware-corrupted: option<u64>,
        anon-huge-pages: option<u64>,
        shmem-huge-pages: option<u64>,
        shmem-pmd-mapped: option<u64>,
        file-huge-pages: option<u64>,
        file-pmd-mapped: option<u64>,
        huge-pages-total: u64,
        huge-pages-free: u64,
        huge-pages-rsvd: u64,
        huge-pages-surp: u64,
        huge-page-size: u64,
        huge-tlb: u64,
        direct-map4k: option<u64>,
        direct-map2-m: option<u64>,
        direct-map1-g: option<u64>,
    }

    get-memory-info: func() -> result<memory-info, string>;
}